[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "aita"
version = "0.1.4"
description = "AI Powered Data Platform"
readme = "README.md"
authors = ["aita <contact@project-aita.com>"]
license = "Apache Software License 2.0"
repository = "https://github.com/project-aita/aita"
homepage = "https://www.project-aita.com"

keywords = ["Artificial Intelligence", "Data Analysis", "Code Generation"]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]

packages = [
    { include = "aita" },
    { include = "aita_lab" }
]

[tool.poetry.scripts]
aita_lab = "aita_lab.cli:main"


[tool.poetry.dependencies]
python = "^3.9"
mock = "^5.1.0"
openai = "^1.33.0"
pydantic = "^2.7.1"
jupyter-ai-magics = "^2.19.0"
pandas = "^2.2.2"
langchain-openai = "^0.1.7"
langchain = "^0.2.9"
langgraph = "^0.1.9"
adbc-driver-sqlite = "^1.0.0"
ipython = "8.14.0"
pyarrow = "^16.1.0"
typer = "^0.12.3"
types-setuptools = "^70.0.0.20240524"
amundsen-databuilder = "^7.5.0"

# extra dependencies
boto3 = { version = "^1.34.122", optional = true }
adbc-driver-postgresql = { version = "^1.0.0", optional = true }
adbc-driver-snowflake = { version = "^1.0.0", optional = true }
findspark = { version = "^2.0.1", optional = true }
pyspark = { version = "^3.2.0", optional = true }

[tool.poetry.group.aita_lab]
optional = true

[tool.poetry.group.aita_lab.dependencies]
alembic = "^1.13.1"
reflex = "^0.5.5"
transformers = "^4.40.2"
sql-metadata = "^2.11.0"
feast = "^0.39.1"

[tool.poetry.extras]
dynamodb = ["boto3"]
postgresql = ["adbc-driver-postgresql"]
snowflake = ["adbc-driver-snowflake"]
pyspark = ["findspark", "pyspark"]
aita_lab = ["aita_lab"]

[tool.poetry.group.test.dependencies]
pytest = "^8.1.1"
pytest-cov = "^3.0.0"
pytest-html = ">=3.1.1,<5.0.0"
coverage = "^7.5.3"
coverage-badge = "^1.1.0"
openai-responses = "^0.6.0"
typing-extensions = "^4.12.1"
pandas = "^2.2.2"
pyspark = "^3.2.0"
findspark = "^2.0.1"


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
bandit = "^1.7.1"
black = "^24.2.0"
darglint = "^1.8.1"
isort = { extras = ["colors"], version = "^5.10.1" }
mypy = "^1.9.0"
pre-commit = "^3.7.1"
pydocstyle = "^6.1.1"
pylint = "^3.2.2"
pytest = "^8.1.1"
pyupgrade = "^2.29.1"
safety = "^1.10.3"
coverage = "^7.5.3"
coverage-badge = "^1.1.0"
pytest-html = ">=3.1.1,<5.0.0"
pytest-cov = "^3.0.0"
openai-responses = "^0.6.0"
typing-extensions = "^4.12.1"
azure-identity = "^1.16.0"
adbc-driver-snowflake = { version = "^1.0.0"}


[tool.black]
# https://github.com/psf/black
target-version = ["py39"]
line-length = 100
color = true

exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | env
    | venv
    | research
)/
'''

[tool.isort]
# https://github.com/timothycrosley/isort/
py_version = 39
line_length = 100

known_typing = ["typing", "types", "typing_extensions", "mypy", "mypy_extensions"]
sections = ["FUTURE", "TYPING", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
include_trailing_comma = true
profile = "black"
multi_line_output = 3
indent = 4
color_output = true

[tool.mypy]
# https://mypy.readthedocs.io/en/latest/config_file.html#using-a-pyproject-toml-file
python_version = 3.9
pretty = true
show_traceback = true
color_output = true

allow_redefinition = false
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
ignore_missing_imports = true
implicit_reexport = false
no_implicit_optional = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
strict_equality = true
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

exclude = [
    "aita_lab",
    "research",
]


[tool.pytest.ini_options]
# https://docs.pytest.org/en/6.2.x/customize.html#pyproject-toml
# Directories that are not visited by pytest collector:
norecursedirs = ["hooks", "*.egg", ".eggs", "dist", "build", "docs", ".tox", ".git", "__pycache__"]
doctest_optionflags = ["NUMBER", "NORMALIZE_WHITESPACE", "IGNORE_EXCEPTION_DETAIL"]

# Extra options:
addopts = [
    "--strict-markers",
    "--tb=short",
    "--doctest-modules",
    "--doctest-continue-on-failure",
]

[tool.coverage.run]
source = ["tests"]

[coverage.paths]
source = "aita"

[coverage.run]
branch = true

[coverage.report]
fail_under = 50
show_missing = true
