# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and publish ui image 

on:
  push:
    branches:
      - main
    paths:
      - 'ui/**'
      - '.github/workflows/main_aita-ui.yml'
  workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: "monorepo/ui"
  COMMIT_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: ./ui

    steps:
      - uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: aitaregistry.azurecr.io
          username: aitaui
          password: ${{ secrets.AZURE_CR_PASSWORD }}

      - name: docker build image
        run: |
          docker build --platform linux/amd64 ./ -t aita-ui --build-arg APP_ENV=production

      - name: Set up Docker Build
        run: |
          docker tag aita-ui aitaregistry.azurecr.io/aita-ui:${{ env.COMMIT_SHA }}

      - name: Publish to Azure Container Registry
        run: |
          docker push aitaregistry.azurecr.io/aita-ui:${{ env.COMMIT_SHA }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
            
      - name: deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: aitaregistry
          containerAppName: aita-demo 
          resourceGroup: aita
          imageToDeploy: aitaregistry.azurecr.io/aita-ui:${{ env.COMMIT_SHA }}